#!/usr/bin/env bash

# ============================================================================
# tools/cursor/adapt/hook-bridge.sh — Cursor hook shim
# ============================================================================
# Static tooling code (like rule-to-mdc.sh / agent-to-mode.sh themselves) —
# copied VERBATIM into <target-repo>/.cursor/hooks/_bridge.sh by
# hook-to-cursor.sh on every run. Never hand-edit the copy in a target repo;
# edit this file and re-run setup-repo.sh / tools/cursor/enable.sh.
#
# Purpose: registry/hooks/{pre,post}-tool-use/*.sh (already copied verbatim
# into <target-repo>/.claude/hooks/... by setup-repo.sh) are Claude Code's
# hook contract: read a JSON payload from stdin, exit 2 + a message on
# stderr to BLOCK, exit 0 to allow. This shim invokes one of those already
# -copied scripts unchanged (no logic duplicated, no logic forked) and
# translates its exit code into Cursor's contract.
#
# Cursor's preToolUse/postToolUse contract — verified against
# https://cursor.com/docs/hooks 2026-08-24 (see docs/tool-compatibility.md
# for the full citation):
#   - Project hooks run with CWD = the repo root, so the relative
#     ".claude/hooks/..." path passed as $1 resolves correctly.
#   - Input: JSON on stdin with (at least) `tool_name` + `tool_input`. This
#     is already the same field-name shape registry/hooks/*.sh scripts
#     already parse (Claude Code's own schema) — the payload is piped
#     through UNCHANGED, no transformation needed for the input side.
#   - Exit code 2 == {"permission":"deny"} automatically, no stdout JSON
#     required — but we print one anyway (with the blocked reason as
#     user_message/agent_message) since the schema allows it and it's
#     better UX than a silent deny.
#   - Exit code 0 == allow, and the docs say "use JSON output" on stdout —
#     so stdout must be empty or valid JSON, never a script's plain-text
#     debug/lint output (e.g. lint-after-write.sh's `echo "→ Linting..."`).
#     Any stdout/stderr the underlying script produces is therefore
#     captured and re-emitted on OUR stderr (visible in Cursor's hook debug
#     logs), never mixed into the stdout we control.
#   - Any other exit code == the hook "failed"; Cursor lets the action
#     proceed by default (fail OPEN) unless the hooks.json entry sets
#     failClosed:true. registry/hooks/*.sh scripts only ever exit 0 or 2
#     today, so this path isn't expected to trigger — logged to stderr in
#     case a future hook adds a different exit code without updating this
#     comment.
#
# NOT hands-on verified inside a live Cursor session (no automation surface
# for that from this environment as of this writing) — built and reasoned
# against the official schema docs only. Do one real smoke test in Cursor
# (trigger a Write that should be blocked) before relying on this for
# security enforcement; see docs/tool-compatibility.md's Fase 1 entry.
#
# Usage (wired via .cursor/hooks.json — generated by hook-to-cursor.sh, do
# not hand-write hooks.json):
#   bash .cursor/hooks/_bridge.sh <underlying-script-relative-path>
# ============================================================================

set -uo pipefail

TARGET="${1:-}"

if [ -z "$TARGET" ]; then
  echo "_bridge.sh: missing required argument (underlying hook script path)" >&2
  echo '{"permission":"allow"}'
  exit 0
fi

if [ ! -f "$TARGET" ]; then
  echo "_bridge.sh: underlying hook script not found: $TARGET (cwd: $(pwd))" >&2
  echo '{"permission":"allow"}'
  exit 0
fi

PAYLOAD="$(cat)"
OUTPUT="$(printf '%s' "$PAYLOAD" | bash "$TARGET" 2>&1)"
EXIT_CODE=$?

if [ -n "$OUTPUT" ]; then
  echo "$OUTPUT" >&2
fi

if [ "$EXIT_CODE" -eq 2 ]; then
  # First non-empty line is normally the most specific part of the message
  # (registry/hooks/*.sh scripts print a "Blocked: ..." summary line first,
  # a generic follow-up tip after — see block-secrets.sh) — good enough as
  # a one-line reason without needing real JSON escaping for a whole
  # multi-line block. Quotes/backslashes are escaped; newlines can't appear
  # since we took one line.
  REASON="$(printf '%s\n' "$OUTPUT" | grep -v '^[[:space:]]*$' | head -1 | sed 's/\\/\\\\/g; s/"/\\"/g')"
  [ -n "$REASON" ] || REASON="Blocked by $TARGET (see stderr for details)."
  printf '{"permission":"deny","user_message":"%s","agent_message":"%s"}\n' "$REASON" "$REASON"
  exit 2
fi

if [ "$EXIT_CODE" -ne 0 ]; then
  echo "_bridge.sh: $TARGET exited $EXIT_CODE (neither 0 nor 2) — allowing (fail-open unless failClosed:true in hooks.json)." >&2
fi

echo '{"permission":"allow"}'
exit 0
